### PR TITLE
I replaced AMA Session markdown for link to PDF files on Google Drive

### PR DESCRIPTION
**Pull request by alexanderluna**
I removed the AMA session markdown files and replaced them by a PDF file of the AMA sessions on Google Drive. I also included the latest AMA session in a separate PDF file because Udacity mixed the Android Scholarship and the Web Specialist AMA file for some reason:

For more info read this Udacity forum post: https://discussions.udacity.com/t/q-a-thrid-ama-session-on-slack/478244

For a preview of the file: https://github.com/Mycroft1891/awesome-google-mobile-web-challenge-links-2017/blob/master/ama-sessions/README.md

### CODE REVIEW

**Comment by RusPosevkin** [comment]
@Mycroft1891 Session #3 was in Thursday 16/11 at 3:30pm-5:30pm CET. In your commit you remove this info. I think the better decision not to remove existing information and just add new info.

**Comment by RusPosevkin** [comment]
And current text formatting is more readable than link to some pdf.

**Comment by Agheb** [comment]
yes, i agree with @RusPosevkin:
*  PDFs are not mobile-friendly vs GitHub pages
*  Each session should be listed by date and in a separate file

For better text formatting, i can recommend  [pandoc](http://pandoc.org). 
Here's an example i converted from Markdown to PDF with Pandoc:

image 2017-12-07 at 7 23 38 pm

**Comment by alexanderluna** [comment]
hmm, ok. In a previous issue we all agreed that we would move to PDFs to not copy and paste so much into the repo. So you want a copy into a separate markdown file ?

**Comment by alexanderluna** [comment]
Here is the issue we decided that: https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/issues/28

**Comment by alexanderluna** [comment]
@RusPosevkin Yes, my bad I made an error when I fixed the merge conflict

**Comment by Agheb** [comment]
you're right but some things have changed e.g AMAs are not happening frequently like we expected.
And i'm OCD about PDFs: the generated pdf from GoogleDrive looks horrible and is a bad choice for mobile devices. 

I suggest to use something like Pandoc to have at least better looking pdfs. 

Thoughts @jvaes @DomanskaGrzyb  ?

**Comment by alexanderluna** [comment]
Sure, let me know I can change ^^

**Comment by RusPosevkin** [comment]
@Mycroft1891 Yep, in my opinion the separate markdown file is better than link to PDF. It contains static information that won't change. 
Anyway, previous information should be saved.

**Pull request closed without merging**
