### PR TITLE
Book: Understanding ECMAScript 6

### PR DESCRIPTION
**Pull request by kshpikat**
* Book by Nicholas C. Zakas (principal architect at Box) about all the heavy changes in ES6. 
* Was proposed a few times on resourses slack channel and on forum. 
* I would like to recommend it because I found it much easier to understand comparing to MDN

### CODE REVIEW

**Comment by jvaes** [comment]
@kshpikat Thank you for your commit. Unfortunately i have some remarks before we can merge your PR:

- Briefly write a description and why it should be added to the list

Please make sure you read the contribution guidelines before submitting a PR next time.

**Comment by kshpikat** [comment]
Hi @jvaes! Thank you for feedback! I never contributed before into open-source projects so was not aware of contribution guidelines. I apologize for inconvenience. 

I updated the description and also fixed the link to free available book online.
Please let me know if there is something more I need to do.

Thank you!

**Comment by Agheb** [comment]
LGTM 👍

**Comment by jvaes** [comment]
Thanks for your contribution @kshpikat

**Pull request merged**
