### PR TITLE
Add Service Worker notes after class

### PR DESCRIPTION
**Pull request by alexanderluna**
I just finished the service worker lesson and saved my notes in the serviceWorker/README.md

### CODE REVIEW

**Review by bogdaaamn — APPROVED** [review]
Thank you for the notes!

**Comment by Agheb** [comment]
Thanks for your notes. I'm not sure about this because  [Awesome lists](https://github.com/sindresorhus/awesome/blob/master/awesome.md) are curated lists of links.  I suggest creating an extra section specifically for class notes.

**Comment by alexanderluna** [comment]
The notes are not really long (50 lines maybe) plus in those 50 lines I included some useful links and code snippets. I didn't want to add all my notes just an overview of how Service Workers work.

PS: If you want to take a look at the finished README take a look at my fork: https://github.com/Mycroft1891/awesome-google-mobile-web-challenge-links-2017/blob/master/serviceWorker/README.md

**Comment by Agheb** [comment]
@Mycroft1891  A brief summary for each chapter. I like it very much !  Let @DomanskaGrzyb have the final word on this (i've already made the request for a review)

**Comment by adomanskagrzyb** [comment]
A brief summary and list of useful links is a great idea. Thank you!

**Pull request merged**
