### PR TITLE
Update grammar, typos and formatting

### PR DESCRIPTION
**Pull request by mimischi**
Hey everyone!

Just though I'd spice up `README.md` and `contributors.md` slightly by changing some grammar, fixing typos and formatting.

I'll have a look at the rest soon!

### CODE REVIEW

**Comment by mimischi** [comment]
I'll probably first go through all files, before this should be merged. I can then squash all commits into a single one, if you'd like!

Also one thing I just noticed, [this paragraph](https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/tree/master/functions#classes) ends without the promised example code.

**Comment by Agheb** [comment]
@mimischi  Awesome work! very important, but often overlooked. I think you should capitalize headings and titles according to this [Capitalize my Title](https://capitalizemytitle.com/)
What do you think?

**Comment by mimischi** [comment]
I prefer titles to not be capitalized, but have never had a look at the actual rules. I don't have any problems with re-adding the title capitalization again :)

**Comment by Agheb** [comment]
@mimischi  No need. I re-added the title capitalization only for the repo's readme. I think that's fine for now.

**Comment by Agheb** [comment]
@mimischi  Again Thank you ! I'll look into it (the paragraph)

**Pull request merged**
