### PR TITLE
Added 2 courses

### PR DESCRIPTION
**Pull request by dragosbus**
Added 2 courses from scotch.io for JS

### CODE REVIEW

**Comment by Agheb** [comment]
@dragosbus Thanks for your first commit. Unfortunately i have some remarks before we can merge your PR:
- The section `Further Learning` covers advanced stuff based on this course
- Scotch.io seems to have a paywall. I could not access the full course content and this might be a dealbreaker for most of us.

**Comment by dragosbus** [comment]
I dosn't have a paywal
I can acces the course without pay.An there are even more advanced things

**Comment by Agheb** [comment]
Please go ahead and submit other advanced resources to the Further Learning section. 
However, both courses are for beginners and at least one of them is freemium. Take a look here:
image 2017-11-13 at 11 47 06 am

 
[Contributing Guidelines](https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/blob/master/contributing.md)

**Comment by dragosbus** [comment]
Module pattern course

**Comment by Agheb** [comment]
@dragosbus  two more things and you're good to go:
- briefly describe your resource in the comments 
- edit your PR title  according to the new resource you submitted

Please make sure you read the contribution guidelines before submitting a PR next time.

**Comment by Agheb** [comment]
I’m closing this PR for now because of inactivity.
@dragosbus  we can reopen it though ! 👍   If you need any help, please DM me on Slack ! Thank you

**Pull request closed without merging**
