### PR TITLE
Further learning

### PR DESCRIPTION
**Pull request by moumen-soliman**
Further learning

### CODE REVIEW

**Comment by jvaes** [comment]
@moumen-soliman amazing work on adding all these links, but sadly I have some remarks before we can merge your pull request:

- maintain the structure we have set up.
- further links should be about advanced topics based on the prior knowledge from the course

@Agheb is working on the contribution guideline. Because of the size of your contribution I suggest you wait for the contribution guideline before submitting your next changes.

**Comment by moumen-soliman** [comment]
@jvaes I'm happy for this edits, so I following some instructions to add these data or links, but if you looking for it, it topics almost based on course already, it called *Further learning*, about advanced topics you are right I promise I will do it next commits  👍

**Comment by alexanderluna** [comment]
Please review your changes, many of your links are about promises and callbacks which don't belong to the further learning section but introduction. Please also don't link to npm packages since we are recollecting resource links not packages. Also among the links you added, some are duplicates of what we already have please remove those. Thank you for your time and effort.

**Comment by Agheb** [comment]
I discussed it with @moumen-soliman and we'll go ahead with PR #66

**Pull request closed without merging**
