### PR TITLE
Add link to Egghead Video Courses

### PR DESCRIPTION
**Pull request by RusPosevkin**
Hello, This PR adds link to Getting Started with Redux Course to Courses section.

### CODE REVIEW

**Comment by Agheb** [comment]
@RusPosevkin  Thanks for your first PR 🎉 
Unfortunately i can't accept your submission at this time:
- No brief description and why the resource should be added
- Egghead seems have to paywall. This might be a dealbreaker coming from udacity's free courses

Please make sure you read the contribution guidelines before submitting a PR.

**Comment by RusPosevkin** [comment]
@Agheb Sorry for my inattention.  
1. I fixed the description.
2. Egghead.io includes a lot of free courses. For example: https://egghead.io/courses/getting-started-with-redux

**Comment by Agheb** [comment]
Can you add a direct link to the Redux course instead of a general link to the site ? 
BTW, great find !

**Comment by Agheb** [comment]
LGTM

**Comment by RusPosevkin** [comment]
@Agheb It's done. PR description is also fixed

**Pull request merged**
