### PR TITLE
Move `getting started` links to separate folder

### PR DESCRIPTION
**Pull request by adomanskagrzyb**
I thought that it may be useful to move `getting started` to separate folder and separate readme - we could add more links, like for example those that you suggested @Agheb ([How to use GIT and Github](https://www.udacity.com/course/how-to-use-git-and-github--ud775), [Writing READMEs](https://www.udacity.com/course/writing-readmes--ud777))

### CODE REVIEW

**Review by Agheb — COMMENTED** [review]
Can we delete the getting started section and move its content into the introduction section ?

**Comment by Haitec** [comment]
I'm not sure if (new) users will find the `getting started` in another section.
The question is: **Where would you like to find informations to start, when you are new to it?**

**Comment by adomanskagrzyb** [comment]
@Haitec yeah, you're right that it will be easier to keep them on the top of the main README, the issue is that I'd like to add more links and I think it could become messy. Any other ideas how to avoid a mess and add more links for newcomers?

**Comment by alexanderluna** [comment]
Introduction sounds good, it is at the top of the list and if there is no 'getting started' link that would be the first place a new user would go to I think.

**Comment by alexanderluna** [comment]
We could change the link (only the link not the text) for ```getting started ``` to ```introduction``` and at the top of the ```introduction```page we can add the ```getting started``` link and all other resources to get started. The ```introduction``` folder is empty anyway so we can use it for that. What do you think ?

**Comment by adomanskagrzyb** [comment]
Ok, I'll take care of it today/tomorrow.

**Comment by Agheb** [comment]
Fix 88ea043277608568619dd7a4a0583d000dd98b5b

**Pull request closed without merging**
